# Specify version via build argument
ARG UBUNTU_VERSION=24.04

# Use the specified version with the correct SHA256 digest
FROM ubuntu:${UBUNTU_VERSION}@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab

# Set labels
LABEL version=${UBUNTU_VERSION}
LABEL release_date="20240801"

# Install packages
RUN apt-get update && apt-get install -y \
    curl \
    vim \
  && apt-get clean

# Default command
CMD ["/bin/bash"]
